trigger: none

variables:
  - group: azure

pool:
  vmImage: ubuntu-latest

resources:
 pipelines:
   - pipeline: bowl-ci # var name to eventually use in the deployment job
     source: bowl-ci # exact name of the pipeline resource
     trigger: none
     # trigger:
     #   branches:
     #     include:
     #       - master

jobs:
    - deployment:
      displayName: Deploy on Azure
      environment: azure # Name of the pipeline environment (created in devops portal)
      strategy:
       runOnce:
           deploy:
               steps:
                - script: |
                    curl -X POST -H "Content-Type: application/octet-stream" -u '$(bowl.user):$(bowl.pwd)' -T $(Pipeline.Workspace)/bowl-ci/bowl/bowl.zip https://$(bowl.host).scm.azurewebsites.net/api/zipdeploy
