trigger:
  branches:
    include:
      - master
  paths:
    include:
      - src/bowl
      - package.json
      - package-lock.json
      - turbo.json
      - '.azure/*'  

variables:
  - group: azure

pool:
 vmImage: 'ubuntu-latest'

stages:
- stage: Build_Push
  displayName: Build and push docker image
  variables:
    tag: 'py'
  jobs:
  - job: Build_Push
    condition: true
    displayName: Build/Push
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'acr-ws-ai'
        command: 'login'
      displayName: acr login
    - script: |
          docker build --progress=plain -f ./src/bowl/Dockerfile-$(tag) -t $(AZURE_CONTAINER_REGISTRY)/$(AZURE_WEBAPP):$(tag)  .
      displayName: build bowl
    - script: |
          docker push $(AZURE_CONTAINER_REGISTRY)/$(AZURE_WEBAPP):$(tag)
      displayName: push bowl
