trigger: none

variables:
  - group: azure

pool:
 vmImage: 'ubuntu-latest'

stages:
- stage: Deploy
  displayName: deploy robot app
  variables:
    tag: 'main'
  jobs:
  - job: Restart
    condition: true
    displayName: restart app
    steps:
    - task: AzureCLI@2
      displayName: Deploy main/staging slot
      inputs:
        azureSubscription: 'arm-ws-ai-ambassador'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: |
         az webapp restart --name $(AZURE_ROBOTAPP) --resource-group $(AZURE_RESOURCE_GROUP)
         #az webapp restart --name $(AZURE_ROBOTAPP) --resource-group $(AZURE_RESOURCE_GROUP) --slot $(AzAppSlot)
