trigger:
  branches:
    include:
      - master
  paths:
    include:
      - src/robot

variables:
  - group: azure
  - name: DOCKER_BUILDKIT
    value: 1
  - name: BUILD_CACHE_KEY
    value: 'robot-cache-v1'

pool:
 vmImage: 'ubuntu-latest'

stages:
- stage: Build_Push
  displayName: Build and push docker image
  jobs:
  - job: Build_Push
    condition: true
    displayName: Build/Push
    steps:
    - task: Cache@2
      inputs:
        key: 'docker | "$(BUILD_CACHE_KEY)"'
        path: $(Pipeline.Workspace)/docker-cache
        restoreKeys: |
          docker | "$(BUILD_CACHE_KEY)"
      displayName: cache docker layers
    - script: |
        mkdir -p $(Pipeline.Workspace)/docker-cache
      displayName: create cache directory
    - script: |
          docker login $(AZURE_CONTAINER_REGISTRY) --username $(AZURE_CONTAINER_REGISTRY_USER) --password-stdin <<< $(AZURE_CONTAINER_REGISTRY_PWD)
      displayName: acr login
    - script: |
        #create new builder instance with proper driver
        docker buildx create --use --driver docker-container --driver-opt network=host
        #build with cache and push
        docker buildx build --progress=plain \
          --push \
          --cache-from type=local,src=$(Pipeline.Workspace)/docker-cache \
          --cache-to type=local,dest=$(Pipeline.Workspace)/docker-cache,mode=max \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          -f ./src/robot/Dockerfile \
          -t $(AZURE_CONTAINER_REGISTRY)/$(AZURE_ROBOTAPP) \
          .
      displayName: build robot with cache & push
