FROM node:18.16.0 AS base
RUN apt update && apt install -y python3.11 python3.11-venv python3-pip && npm install pm2 -g

FROM base as builder
WORKDIR /app
COPY *.json ./
COPY src/bowl ./src/bowl
RUN npm ci --legacy-peer-deps=true
# build
RUN npm run build:bowl
#llm
ENV PYTHON=python3.11
RUN cd ./src/bowl/payload && npm run dev:llm

FROM base as runtime
WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/src/bowl/payload/dist ./
COPY --from=builder /app/src/bowl/payload/build ./build
COPY --from=builder /app/src/bowl/payload/venv ./venv
COPY --from=builder /app/src/bowl/payload/lib ./lib
COPY --from=builder /app/src/bowl/payload/.env* ./
ENV NODE_ENV=production
ENV PYTHON=python3.11
EXPOSE 4000
ENV PORT 4000
ENV HOSTNAME "0.0.0.0"
CMD ["pm2-runtime", "server.js"]
