FROM python:3.11-slim AS base
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update; \
  apt-get full-upgrade -y; \
  apt-get install -y --no-install-recommends \
  ca-certificates \
  curl \
  tesseract-ocr \
  poppler-utils \
  ; \
  apt-get clean; \
  rm -rf /var/lib/apt/lists/*

ENV NODE_VERSION v18.16.0
ENV NVM_DIR /usr/local/nvm

RUN mkdir -p "$NVM_DIR"; \
  curl -o- \
  "https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh" | \
  bash \
  ;
RUN /bin/bash -c "source $NVM_DIR/nvm.sh && nvm install $NODE_VERSION && nvm use --delete-prefix $NODE_VERSION"
ENV NODE_PATH $NVM_DIR/versions/node/$NODE_VERSION/bin
ENV PATH $NODE_PATH:$PATH

FROM base as builder
WORKDIR /app
COPY *.json ./
COPY src/packages ./src/packages
COPY src/bowl ./src/bowl
RUN npm ci --legacy-peer-deps=true
# build
RUN npm run build:bowl

FROM base as runtime
WORKDIR /app
RUN npm install pm2@latest -g
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/src/bowl/payload/dist ./
COPY --from=builder /app/src/bowl/payload/build ./build
COPY --from=builder /app/src/bowl/payload/venv ./venv
COPY --from=builder /app/src/bowl/payload/lib ./lib
COPY --from=builder /app/src/bowl/payload/.env* ./
ENV NODE_ENV=production
EXPOSE 4000
ENV PORT 4000
ENV HOSTNAME "0.0.0.0"
CMD ["pm2-runtime", "server.js"]
