name: robot-ci

on:
  push:
    branches:
      - master
    paths:
      - 'src/robot/**'
  workflow_dispatch:

env:
  DOCKER_BUILDKIT: 1
  BUILD_CACHE_KEY: 'robot-cache-v1'
  REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
  IMAGE_NAME: ${{ secrets.AZURE_ROBOTAPP }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:

    - name: free-up agent space
      run: |
        rm -rf /opt/hostedtoolcache
        swapoff /swapfile
        rm -f /swapfile /usr/share/dotnet /usr/local/lib/android /opt/ghc

    - name: checkout repository
      uses: actions/checkout@v4

    - name: set up docker buildx
      uses: docker/setup-buildx-action@v3

    - name: cache docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ env.BUILD_CACHE_KEY }}
        restore-keys: |
          ${{ runner.os }}-buildx-${{ env.BUILD_CACHE_KEY }}

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USER }}
        password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PWD }}

    - name: build docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./src/robot/Dockerfile
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        load: true
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-copy,mode=max
        build-args: |
          BUILDKIT_INLINE_CACHE=1

    # Issue with cache-to that can grow indefinitely: https://github.com/docker/build-push-action/issues/252
    # move the newly created cache to default cache location
    - name: move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-copy /tmp/.buildx-cache

    - name: push docker image
      run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
